### ISSUE TITLE
SOLUTION NO

### ISSUE THREAD

**Issue by Waffalz** [Waffalz/Seasons#3]
MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAX

THE SOLUTION'S GONE
I CAN'T OPEN IN VISUAL STUDIO
I CAN'T WORK ON TEXTURES WITHOUT KNOWING SIZES
WE'RE ALL GONNA DIE

**Comment by michaelmilton99** [comment]
Calm down, it'll be okay. We can just revert it to get it back
